exception InvalidSyntaxError of string
exception ReservedKeywordError of string
exception UndefinedError of string
exception NameError of string
exception TypeError of string
exception MultiDefinitionsError of string
exception ArgumentNumberError of string
exception RelationError of string
exception AttributeError of string
exception BadAssignmentError of string
exception BadArgumentTypeError of string
exception ElementTypeError of string
