exception InvalidSyntaxError of string
exception ReservedKeywordError of string
exception UndefinedError of string
exception NameError of string
exception TypeError of string
exception MultiDefinitionsError of string
exception ArgumentNumberError of string
exception ArgumentTypeError of string
exception UnexpectedArgumentError of string
exception RequiredArgumentError of string
exception RelationError of string
exception AttributeError of string
exception BadAssignmentError of string
exception ElementTypeError of string
exception QueryReturnTypeError of string
exception QueryArgumentError of string
exception QueryTypeError of string
exception UniqueFieldError of string
exception DeclarationTypeError of string
exception UnexpectedAttributeError of string
exception UnexpectedConfigError of string
exception RequiredFormInputError of string
exception RequiredAuthConfigError of string
exception CompilationError of string
exception UnexpectedEntryError of string
exception RequiredEntryError of string
exception FormInputTypeError of string
